apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commerzbank-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: devops-toolkit/db
    repoURL: https://github.com/tapasmishraarc/combine-infra-services-apps
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
